name: daily-cron
on:
  schedule:
    - cron: "* * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Reminders
        run: |
          curl --request GET \
          --url '/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
